# Generated by Django 5.1.2 on 2024-11-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteAPP', '0002_signup_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_of_orders', models.IntegerField(blank=True, null=True)),
                ('Price_Per_Quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('Total_price', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Sigin_Name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='signup_db',
            name='Sigin_Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
