# Generated by Django 5.1.2 on 2024-11-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteAPP', '0003_cart_db_alter_signup_db_sigin_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_db',
            name='Total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
