# Generated by Django 5.1.2 on 2024-10-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catgory_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Category_Image1', models.ImageField(blank=True, null=True, upload_to='SareePic')),
                ('Category_Image2', models.ImageField(blank=True, null=True, upload_to='SareePic')),
                ('Category_Image3', models.ImageField(blank=True, null=True, upload_to='SareePic')),
            ],
        ),
    ]
