# Generated by Django 5.1.2 on 2024-10-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_of_Product', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Image1', models.ImageField(blank=True, null=True, upload_to='SareePic')),
                ('Product_Image2', models.ImageField(blank=True, null=True, upload_to='SareePic')),
                ('Product_Image3', models.ImageField(blank=True, null=True, upload_to='SareePic')),
            ],
        ),
    ]
