# Generated by Django 5.1.2 on 2024-10-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_product_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sigin_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Sigin_Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Sigin_Mobile', models.IntegerField(blank=True, max_length=100, null=True)),
                ('Sigin_Pswd', models.CharField(blank=True, max_length=100, null=True)),
                ('Sigin_confpswd', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
