# Generated by Django 5.1.2 on 2024-10-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_signup_db'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup_DB',
        ),
    ]
