# Generated by Django 5.1.2 on 2024-11-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_delete_signup_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_db',
            name='Product_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
